name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: main # Ensure the workflow runs on the default branch

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: codecraft-sanju
          outputs: dist/snake.svg

      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Snake Animation"
          file_pattern: dist/snake.svg
          branch: main # Specify the default branch
